### ISSUE TITLE
About learning rate decay

### ISSUE THREAD

**Issue by YE-ck** [Yuliang-Zou/tf_fcn#4]
您好，感谢您提供Tensorflow版本的FCN代码。在您的代码中有些疑问请教您，还得麻烦您解答一下，谢谢。

在train.py中第55-59行
`			if len(loss_list) > 100 and not DECAY:
				avg = sum(loss_list[-100::]) / 100.0
				if avg <= 0.4:
					model.base_lr /= 10
					DECAY = True`
我理解的意思是在训练过程中倒数100次迭代的loss的均值小于等于0.4则将lr缩小10倍，并且根据参数DECAY整个训练过程lr只能改变一次。请问为什么要引入这么一个改变lr的机制呢，不是应当loss不改变的时候再降低lr么？

**Comment by Yuliang-Zou** [comment]
因为在训练过程中我发现loss的波动比较大，所以觉得可能是lr太大了，在loss降到一定程度以后我就把lr变小了。不过这个方法在实验中也没作用，还是把lr设得小一些，用简单的momentum来训练效果好一些。
