### ISSUE TITLE
关于反卷积的一些疑惑

### ISSUE THREAD

**Issue by jsjs0827** [Yuliang-Zou/tf_fcn#5]
我在做小目标检测的深度卷积神经网络，直接用deconv的话，网络不收敛，请问你对此有什么建议吗？

**Comment by Yuliang-Zou** [comment]
不知道你的小目标检测给出的prediction是什么，如果是bounding box的话，不妨看一下这篇paper: https://dl.dropboxusercontent.com/u/7775117/jianxiongxiao.com/projects/2016/SmallObject/paper.pdf
感觉应该没必要用fcn，在faster rcnn的框架下搭建效果应该就不错
